version: '2'
services:
  server:
    build: ./server
  web-client:
    build: ./web-client/
    ports:
      - "3000:3000"
    volumes:
      - ./web-client/:/usr/src/app/
    depends_on:
      - server
