version: '2'
services:
  server:
    build: ./server
    volumes:
      - ./server/:/usr/src/server/
    ports:
      - "5000:5000"
  web-client:
    build: ./web-client/
    ports:
      - "6088:6088"
    volumes:
      - ./web-client/public/:/usr/src/web-client/public/
      - ./web-client/server.js:/usr/src/web-client/server.js
    depends_on:
      - server
